### ISSUE TITLE
If Designite can learn code smell, why do we need a DL model to do it again?

### ISSUE THREAD

**Issue by dany-nonstop** [tushartushar/DeepLearningSmells#1]
thanks for sharing the code and several implementations. I may have missed something about it. Why would we use DL to analyze code smell again, if Designite is already doing its job? What's the additional value besides that we've learned a model similar to Designite?

**Comment by tushartushar** [comment]
Smells can be detected using different methods. Designite uses metrics and fixed heuristics to identify smells. Because of fixed rules, tools such as Designite do not consider subjectivity involved in the detection process. That's why we need DL methods. I hope it helps.
