### ISSUE TITLE
Instruction on running the model

### ISSUE THREAD

**Issue by omeiirr** [tushartushar/DeepLearningSmells#2]
How can I run the trained model to test out a new repository? I could not find any `.h5` files that could be the weights for the DL model. I may be wrong; still pretty new to the field of machine learning and deep learning.

Thanks for your fantastic work!

**Comment by tushartushar** [comment]
Hi Omeiirr,
This repository doesn't contain a trained model. It helps you to build your own dataset and train your own model. Readme file has step-by-step process of doing the same.
Regards.
